"""P9 — Repository and release consistency tests.

Requirements lock:
  - dial/requirements.lock exists, is parseable, and contains all packages
    declared in dial/requirements.txt (direct and transitive dependencies).

Deployed Python entry point imports:
  - All five supervisor scripts can be loaded (syntax + import correctness).
  - Core and dial Python modules import without crashing.

DIAL_PROTOCOL.md schema validation:
  - Every JSON code block in DIAL_PROTOCOL.md is syntactically valid.
  - Key endpoint response and request examples contain the required fields.

Route existence (protocol → code):
  - Every route documented in DIAL_PROTOCOL.md exists in the corresponding
    Python handler file.
  - The /api/audio/status route is in ALLOWLIST_PATHS (unauthenticated per spec).
  - The /api/dial/volume route is NOT in ALLOWLIST_PATHS (UUID-in-body auth).

Not covered here:
  - requirements.lock full reproducibility: requires `pip-compile` and a live
    Python environment — CI-only, not part of offline unit suite.
  - Release archive content: requires `make dist` or `git archive` — CI-only.
  - Multi-Python-version runs: CI matrix with tox — not part of offline suite.
"""
from __future__ import annotations

import importlib.util
import json
import re
import sys
from importlib.machinery import SourceFileLoader
from pathlib import Path
from types import ModuleType
from unittest.mock import MagicMock, patch

import pytest

REPO_ROOT = Path(__file__).parent.parent

sys.path.insert(0, str(REPO_ROOT / "core"))
sys.path.insert(0, str(REPO_ROOT / "dial"))
sys.path.insert(0, str(REPO_ROOT / "tests"))

from conftest import load_supervisor_script


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _extract_json_blocks(markdown: str) -> list[str]:
    """Return the content of every ```json ... ``` block in *markdown*."""
    return re.findall(r"```json\s*\n(.*?)\n```", markdown, re.DOTALL)


# ---------------------------------------------------------------------------
# Requirements lock
# ---------------------------------------------------------------------------

class TestRequirementsLock:
    """dial/requirements.lock must be present, parseable, and consistent."""

    @pytest.fixture(scope="class")
    def lock_path(self):
        p = REPO_ROOT / "dial" / "requirements.lock"
        if not p.exists():
            pytest.skip("dial/requirements.lock not found")
        return p

    @pytest.fixture(scope="class")
    def lock_text(self, lock_path):
        return _read(lock_path)

    @pytest.fixture(scope="class")
    def req_text(self):
        p = REPO_ROOT / "dial" / "requirements.txt"
        if not p.exists():
            pytest.skip("dial/requirements.txt not found")
        return _read(p)

    def test_lock_file_exists(self, lock_path):
        assert lock_path.exists(), "dial/requirements.lock must exist alongside requirements.txt"

    def test_lock_file_is_not_empty(self, lock_text):
        assert lock_text.strip(), "dial/requirements.lock must not be empty"

    def test_lock_file_contains_hash_lines(self, lock_text):
        assert "--hash=sha256:" in lock_text, (
            "dial/requirements.lock must contain --hash= lines "
            "(regenerate with pip-compile --generate-hashes)"
        )

    def test_direct_dependency_pinned_in_lock(self, lock_text, req_text):
        """Every package from requirements.txt appears pinned in requirements.lock."""
        for line in req_text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            pkg = re.split(r"[=<>!;#]", line)[0].strip().lower()
            assert pkg in lock_text.lower(), (
                f"Direct dependency '{pkg}' from requirements.txt "
                "not found in requirements.lock"
            )

    def test_transitive_dep_colorzero_in_lock(self, lock_text):
        """colorzero is a known transitive dep of gpiozero; it must be pinned."""
        assert "colorzero" in lock_text.lower(), (
            "colorzero (transitive dependency of gpiozero) is missing from "
            "dial/requirements.lock; regenerate with pip-compile --generate-hashes"
        )

    def test_lock_file_generated_by_pip_compile(self, lock_text):
        """Confirm the lock file was generated by pip-compile, not written by hand."""
        assert "pip-compile" in lock_text, (
            "requirements.lock header comment must reference pip-compile "
            "(regenerate: pip-compile --generate-hashes dial/requirements.txt -o dial/requirements.lock)"
        )


# ---------------------------------------------------------------------------
# Deployed Python entry point imports
# ---------------------------------------------------------------------------

class TestSupervisorScriptImports:
    """All five supervisor scripts must load without import errors."""

    @pytest.mark.parametrize("script", [
        "autostream_admin",
        "autostream_updater",
        "autostream_dial_updater",
        "autostream_update_retry",
        "autostream_update_support.py",
    ])
    def test_script_loads_without_error(self, script):
        script_path = REPO_ROOT / "supervisor" / script
        if not script_path.exists():
            pytest.skip(f"supervisor/{script} not found")
        alias = f"_p9_{script.replace('.', '_')}"
        if script_path.suffix == ".py":
            loader = SourceFileLoader(alias, str(script_path))
            spec = importlib.util.spec_from_loader(alias, loader)
            mod = importlib.util.module_from_spec(spec)
            _inject_posix_stubs()
            try:
                loader.exec_module(mod)
            except SystemExit:
                pass   # scripts that call sys.exit() at module level
            finally:
                _remove_posix_stubs()
        else:
            try:
                mod = load_supervisor_script(script, alias)
            except SystemExit:
                pass


def _inject_posix_stubs():
    for stub in ("fcntl", "pwd", "grp"):
        if stub not in sys.modules:
            sys.modules[stub] = MagicMock()


def _remove_posix_stubs():
    for stub in ("fcntl", "pwd", "grp"):
        sys.modules.pop(stub, None)


class TestCoreModuleImports:
    """Key core Python modules must import cleanly."""

    @pytest.mark.parametrize("module_name", [
        "autostream_config",
        "autostream_sysutils",
        "autostream_auth",
    ])
    def test_module_imports(self, module_name):
        module_path = REPO_ROOT / "core" / f"{module_name}.py"
        if not module_path.exists():
            pytest.skip(f"{module_name}.py not found")
        # Use the real import mechanism so dataclass module lookups resolve.
        import importlib as _il
        mod = _il.import_module(module_name)
        assert mod is not None


# ---------------------------------------------------------------------------
# DIAL_PROTOCOL.md — JSON example validity
# ---------------------------------------------------------------------------

class TestDialProtocolDocJson:
    """Every JSON example in DIAL_PROTOCOL.md must be syntactically valid."""

    @pytest.fixture(scope="class")
    def doc_path(self):
        p = REPO_ROOT / "docs" / "dial" / "DIAL_PROTOCOL.md"
        if not p.exists():
            pytest.skip("DIAL_PROTOCOL.md not found")
        return p

    @pytest.fixture(scope="class")
    def json_blocks(self, doc_path):
        return _extract_json_blocks(_read(doc_path))

    def test_document_has_json_blocks(self, json_blocks):
        assert len(json_blocks) >= 5, (
            "DIAL_PROTOCOL.md should contain at least 5 JSON examples; "
            f"found {len(json_blocks)}"
        )

    _DIAL_PROTOCOL = REPO_ROOT / "docs" / "dial" / "DIAL_PROTOCOL.md"
    @pytest.mark.parametrize("idx,block", [
        (i, b) for i, b in enumerate(
            _extract_json_blocks(_read(_DIAL_PROTOCOL))
            if _DIAL_PROTOCOL.exists()
            else []
        )
    ])
    def test_json_block_is_valid(self, idx, block):
        try:
            json.loads(block)
        except json.JSONDecodeError as e:
            pytest.fail(
                f"JSON block #{idx} in DIAL_PROTOCOL.md is not valid JSON:\n"
                f"  {e}\n"
                f"Block:\n{block[:200]}"
            )


class TestDialProtocolSchemaFields:
    """Key endpoint examples in DIAL_PROTOCOL.md contain required fields."""

    @pytest.fixture(scope="class")
    def doc_text(self):
        p = REPO_ROOT / "docs" / "dial" / "DIAL_PROTOCOL.md"
        if not p.exists():
            pytest.skip("DIAL_PROTOCOL.md not found")
        return _read(p)

    def _find_json_with_field(self, doc_text: str, field: str) -> list[dict]:
        """Return all parsed JSON blocks that contain *field* at the top level."""
        results = []
        for block in _extract_json_blocks(doc_text):
            try:
                obj = json.loads(block)
            except json.JSONDecodeError:
                continue
            if isinstance(obj, dict) and field in obj:
                results.append(obj)
        return results

    def test_audio_status_example_has_playing_field(self, doc_text):
        matches = self._find_json_with_field(doc_text, "playing")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example with a 'playing' field "
            "for the /api/audio/status response"
        )
        assert isinstance(matches[0]["playing"], bool), (
            "'playing' must be a boolean in the /api/audio/status example"
        )

    def test_audio_status_example_has_outputs_field(self, doc_text):
        matches = self._find_json_with_field(doc_text, "outputs")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example with an 'outputs' field"
        )

    def test_dial_volume_request_has_dial_id_and_delta(self, doc_text):
        matches = self._find_json_with_field(doc_text, "dial_id")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example with a 'dial_id' field "
            "for the /api/dial/volume request"
        )
        assert "delta" in matches[0], (
            "'delta' must appear in the same example as 'dial_id'"
        )

    def test_dial_volume_success_response_has_ok_and_volume(self, doc_text):
        matches = self._find_json_with_field(doc_text, "volume")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example with a 'volume' field "
            "for the /api/dial/volume success response"
        )
        assert "ok" in matches[0], (
            "'ok' must appear in the same example as 'volume'"
        )

    def test_configure_get_response_has_required_fields(self, doc_text):
        matches = self._find_json_with_field(doc_text, "step_percent")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example for GET /configure "
            "containing 'step_percent'"
        )
        required = {"step_percent", "pin_set", "name", "version", "auto_update"}
        missing = required - set(matches[0].keys())
        assert not missing, (
            f"GET /configure example is missing fields: {sorted(missing)}"
        )

    def test_recovery_status_response_has_required_fields(self, doc_text):
        matches = self._find_json_with_field(doc_text, "volume_confirmed")
        assert matches, (
            "DIAL_PROTOCOL.md must have a JSON example for /recovery_status "
            "containing 'volume_confirmed'"
        )
        assert "active" in matches[0], (
            "'active' must appear alongside 'volume_confirmed' in /recovery_status example"
        )

    def test_update_status_response_documents_state_field(self, doc_text):
        # The /update/status example uses pipe notation ("idle"|"running"|...)
        # which is not parseable as JSON. Check for field presence in raw text.
        assert '"state"' in doc_text, (
            "DIAL_PROTOCOL.md must document a 'state' field for /update/status"
        )
        assert '"version"' in doc_text, (
            "DIAL_PROTOCOL.md must document a 'version' field for /update/status"
        )
        # Verify the documented state values are the canonical set
        for state_val in ("idle", "running", "complete", "failed"):
            assert state_val in doc_text, (
                f"DIAL_PROTOCOL.md must document state value '{state_val}' "
                "for GET /update/status"
            )


# ---------------------------------------------------------------------------
# Route existence: protocol → codebase
# ---------------------------------------------------------------------------

class TestDialRouteExistence:
    """Routes documented in DIAL_PROTOCOL.md must exist in dial_http_server.py."""

    @pytest.fixture(scope="class")
    def handler_src(self):
        p = REPO_ROOT / "dial" / "dial_http_server.py"
        if not p.exists():
            pytest.skip("dial_http_server.py not found")
        return _read(p)

    @pytest.mark.parametrize("route", [
        "/configure",
        "/recovery_status",
        "/update/status",
        "/update",
    ])
    def test_dial_route_exists_in_handler(self, handler_src, route):
        assert route in handler_src, (
            f"Route '{route}' documented in DIAL_PROTOCOL.md not found in "
            "dial/dial_http_server.py"
        )


class TestApplianceRouteExistence:
    """Appliance API routes documented in DIAL_PROTOCOL.md must exist in the codebase."""

    @pytest.fixture(scope="class")
    def api_src(self):
        p = REPO_ROOT / "core" / "autostream_webui_api.py"
        if not p.exists():
            pytest.skip("autostream_webui_api.py not found")
        return _read(p)

    def test_audio_status_route_exists(self, api_src):
        assert "/api/audio/status" in api_src, (
            "GET /api/audio/status is missing from autostream_webui_api.py"
        )

    def test_dial_volume_route_exists(self, api_src):
        assert "/api/dial/volume" in api_src, (
            "POST /api/dial/volume is missing from autostream_webui_api.py"
        )


# ---------------------------------------------------------------------------
# Security policy: allowlist matches DIAL_PROTOCOL.md authentication rules
# ---------------------------------------------------------------------------

class TestApiSecurityPolicy:
    """Auth policy for documented routes must match DIAL_PROTOCOL.md."""

    @pytest.fixture(scope="class")
    def auth_module(self):
        import autostream_auth
        return autostream_auth

    def test_audio_status_is_allowlisted(self, auth_module):
        """DIAL_PROTOCOL.md says GET /api/audio/status is 'Unauthenticated'."""
        assert "/api/audio/status" in auth_module.ALLOWLIST_PATHS, (
            "/api/audio/status must be in ALLOWLIST_PATHS — "
            "DIAL_PROTOCOL.md documents it as unauthenticated"
        )

    def test_dial_volume_is_not_allowlisted(self, auth_module):
        """DIAL_PROTOCOL.md says POST /api/dial/volume requires UUID-in-body auth."""
        assert "/api/dial/volume" not in auth_module.ALLOWLIST_PATHS, (
            "/api/dial/volume must NOT be in ALLOWLIST_PATHS — "
            "it requires UUID-in-body authentication per DIAL_PROTOCOL.md"
        )

    def test_audio_status_has_no_session_requirement(self, auth_module):
        """ALLOWLIST_PATHS membership implies no session/CSRF check."""
        from autostream_auth import ALLOWLIST_PATHS
        # Confirm the allowlist is a set-like collection for O(1) lookup
        assert hasattr(ALLOWLIST_PATHS, "__contains__"), (
            "ALLOWLIST_PATHS must support 'in' operator for route checking"
        )
